### ISSUE TITLE
process didn't exit when I killed the vm

### ISSUE THREAD

**Issue by ashraffouda** [LeeSmet/cloud-console#3]
the cloud-console process should auto exit when the pty is released which is not the case
![Screenshot from 2022-12-22 18-00-34](https://user-images.githubusercontent.com/1689456/209173902-a3b7d26e-5df0-45b6-a48b-ffb32ae9862b.png)

**Comment by LeeSmet** [comment]
Process used to exit after 5 seconds, now exits immediately
